{
 "title": "RX Missed Percentage by Host",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RX Dropped Packets Percentage by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(network_interface_stats_rx_dropped[5m])) by (host) / sum(rate(network_interface_stats_rx_packets[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RX Missed Packets Percentage by Host ",
   "type": "timeseries",
   "description": "percentage of missed packets in relation to the overall received packets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(network_interface_stats_rx_missed[5m])) by (host) / sum(rate(network_interface_stats_rx_packets[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RX Dropped Packets by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "network_interface_stats_rx_dropped ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RX Missed Packets by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "network_interface_stats_rx_missed > 0",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Top 5 Dropped: Host - Interface",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(5, max by (host, interface) (network_interface_stats_rx_missed))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX Packets by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(network_interface_stats_rx_packets) by (host)",
     "legendFormat": "{{host}} "
    }
   ]
  }
 ]
}