apiVersion: v1
kind: ServiceAccount
metadata:
  name: blob-uploader-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "your-client-id"  # Replace with actual client ID
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: web-service
  namespace: default
  labels:
    app: web-service
    azure.workload.identity/use: "true"
spec:
  nodeSelector:
    dedicated: web-arm  # Co-schedule with blob uploader
  serviceAccountName: web-service-sa
  containers:
  - name: web-app
    image: nginx:alpine
    ports:
    - containerPort: 8080
      name: http
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: config
    configMap:
      name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        
        location / {
            return 200 '{"message": "Hello from AKS", "timestamp": "$time_iso8601", "host": "$hostname"}';
            add_header Content-Type application/json;
        }
        
        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-service-sa
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
  labels:
    app: web-service
spec:
  selector:
    app: web-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
